modLoader = "javafml"
loaderVersion = "[47,)"
license = "LGPLv3.0"
issueTrackerURL = "https://github.com/JoniCraftHD/luna/issues"

[[mods]]
modId = "luna"
version = "0.1.0"
displayName = "Mission Luna"
displayURL = ""
logoFile = "icon.png"
authors = "JoniCraftHD"
description = '''
Mission Luna - A GregTech CEu Addon
'''

[[dependencies.luna]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.luna]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.luna]]
modId = "gtceu"
mandatory = true
versionRange = "[1.0,)"
ordering = "AFTER"
side = "BOTH"

